export const AGENT_RULES_VERSION = "2.0.0";

export const AGENT_RULES = [
  {
    code: "R001",
    name: "VERIFIED_AGENT_REQUIRED",
    tier: 1,
    action: "BLOCK",
    configurable: true,
    needsLookup: false,
    description:
      "Requires a cryptographically identified buying agent. This is a baseline merchant rule and does not require eIDAS, QTSP, Visa Verifier, or payment-network attestation.",
    when: "agentId is missing OR agentId === 'unknown_agent'",
    defaults: { requireAgentId: true },
    merchantPolicyKey: "r001",
    merchantConfig: "requireAgentId (default true)",
    examples: [
      "Anonymous agent checkout -> BLOCK",
      "did:web agent token present -> PASS",
    ],
  },
  {
    code: "R002",
    name: "SIGNATURE_SPOOF_BLOCK",
    tier: 2,
    action: "BLOCK",
    configurable: false,
    needsLookup: false,
    description:
      "Blocks missing, malformed, or invalid agent-token signatures.",
    when: "agent token is present but signature validation fails",
    defaults: { requireValidSignature: true },
    merchantPolicyKey: "r002",
    merchantConfig: "requireValidSignature (fixed true for production)",
    examples: [
      "tampered AgentToken JWS -> BLOCK",
      "valid AgentToken JWS -> PASS",
    ],
  },
  {
    code: "R003",
    name: "MANDATE_BOUNDARY_MATCH",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: false,
    description:
      "Blocks carts that exceed signed user or merchant mandate boundaries.",
    when: "cartTotalCents > maxAmountCents OR category outside allowedCategories",
    defaults: {},
    merchantPolicyKey: "r003",
    merchantConfig: "maxAmountCents, allowedCategories",
    examples: ["Cart EUR 250 with mandate max EUR 100 -> BLOCK"],
  },
  {
    code: "R004",
    name: "NEW_KEY_FRICTION",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: false,
    description:
      "Escalates agents using a first-seen or recently rotated signing key. Platforms track each key's first observation via WP transient (WC), APCu (PS), or ir.config_parameter (Odoo); the age in hours is sent as _agent_key_age_hours.",
    when: "agent key age is below maxKeyAgeHours",
    defaults: { maxKeyAgeHours: 24 },
    merchantPolicyKey: "r004",
    merchantConfig: "maxKeyAgeHours (default 24)",
    examples: ["Agent key first seen 2h ago -> BLOCK"],
  },
  {
    code: "R005",
    name: "REVOKED_AGENT_BLOCK",
    tier: 2,
    action: "BLOCK",
    configurable: false,
    needsLookup: false,
    description:
      "Blocks agents marked as revoked or suspended by Trusteed or a configured identity provider. Also triggers when enforcement_events shows 3+ R001 BLOCK decisions for this agent in the last 7 days.",
    when: "agent status is revoked or suspended",
    defaults: {},
    merchantPolicyKey: "r005",
    merchantConfig: "not merchant-configurable",
    examples: ["Revoked agent DID -> BLOCK"],
  },
  {
    code: "R006",
    name: "PROVIDER_CONFIDENCE_TIER",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: false,
    description:
      "Requires a minimum Trusteed trust score or provider confidence level.",
    when: "agentTrustScore < minScore OR providerConfidence < minProviderConfidence",
    defaults: { minScore: 30, minProviderConfidence: 0.6 },
    merchantPolicyKey: "r006",
    merchantConfig: "minScore, minProviderConfidence",
    examples: ["Agent trustScore 20 with minScore 30 -> BLOCK"],
  },
  {
    code: "R007",
    name: "CROSS_MERCHANT_ABUSE_SIGNAL",
    tier: 1,
    action: "BLOCK",
    configurable: true,
    needsLookup: true,
    description:
      "Blocks agents with a cross-merchant abuse signal. Server queries enforcement_events for agents blocked by 2+ distinct merchants in the last 30 days. Also checks _cross_merchant_abuse platform attribute.",
    when: "crossMerchantAbuseSignal is true",
    defaults: {},
    merchantPolicyKey: "r007",
    merchantConfig: "enabled only after legal/data-sharing approval",
    examples: ["Known refund-abuse cluster signal -> BLOCK"],
  },
  {
    code: "R008",
    name: "SCOPE_ESCALATION_DETECTION",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: false,
    description:
      "Blocks checkout actions outside the declared agent scope. The JWT scope claim is extracted by the platform module and sent as _requested_scopes. Merchants configure allowedScopes to restrict which scope values are permitted.",
    when: "requestedScopes contains a scope not in allowedScopes",
    defaults: {},
    merchantPolicyKey: "r008",
    merchantConfig: "allowedScopes",
    examples: ["Agent asks for checkout:write without scope -> BLOCK"],
  },
  {
    code: "R009",
    name: "AGENT_VERIFICATION_REQUIRED",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: false,
    description:
      "Merchant-friendly baseline requiring agent identity on agentic checkout paths.",
    when: "agentic checkout AND no verified agent identity",
    defaults: { requireAgentId: true },
    merchantPolicyKey: "r009",
    merchantConfig: "requireAgentId (default true)",
    examples: ["Shopify cart from agent endpoint with no agent token -> BLOCK"],
  },
  {
    code: "R010",
    name: "NEW_AGENT_PROBATION",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: true,
    description:
      "Adds friction to agents with no merchant-specific purchase history.",
    when: "completedOrders(agentId, merchantId) < minCompletedOrders",
    defaults: { minCompletedOrders: 0 },
    merchantPolicyKey: "r010",
    merchantConfig:
      "minCompletedOrders — default 0, so an unconfigured R010 is a no-op (was 1 historically)",
    examples: ["First purchase by a new agent -> BLOCK or review"],
  },
  {
    code: "R011",
    name: "REPEAT_FAILED_CHECKOUT",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: true,
    description: "Blocks agents with too many recent failed checkout attempts.",
    when: "failedCheckoutCount(agentId, windowSeconds) > maxAttempts",
    defaults: { windowSeconds: 300, maxAttempts: 3 },
    merchantPolicyKey: "r011",
    merchantConfig: "windowSeconds, maxAttempts",
    examples: ["5 failed checkouts in 5 minutes -> BLOCK"],
  },
  {
    code: "R012",
    name: "HIGH_RISK_CATEGORY",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: false,
    description:
      "Escalates carts containing merchant-defined high-risk product categories.",
    when: "cart category is in categories",
    defaults: { categories: [] },
    merchantPolicyKey: "r012",
    merchantConfig: "categories",
    examples: ["Gift cards category enabled as high risk -> BLOCK"],
  },
  {
    code: "R013",
    name: "RETURN_POLICY_GUARD",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: false,
    description:
      "Blocks carts with final-sale/virtual products when the agent token does not declare return_policy: final_sale. Platform modules detect non-refundable products and compare against the JWT return_policy claim.",
    when: "returnPolicyMismatch is true",
    defaults: { disallowFinalSaleMismatch: true },
    merchantPolicyKey: "r013",
    merchantConfig: "disallowFinalSaleMismatch",
    examples: ["Agent expects free return on final-sale item -> BLOCK"],
  },
  {
    code: "R014",
    name: "DELIVERY_RISK_GUARD",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: true,
    description:
      "Blocks risky delivery destinations or repeated post-shipment cancellation patterns.",
    when: "shipping country is high risk OR cancelCount exceeds maxCancellations",
    defaults: {
      highRiskCountries: ["KP", "IR", "SY", "CU"],
      windowDays: 90,
      maxCancellations: 3,
    },
    merchantPolicyKey: "r014",
    merchantConfig: "highRiskCountries, windowDays, maxCancellations",
    examples: ["Delivery to blocked country -> BLOCK"],
  },
  {
    code: "R015",
    name: "PRICE_CHANGE_GUARD",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: false,
    description:
      "Escalates carts where price moved after the agent discovered the product. WC snapshots prices in session on cart load; PS uses a per-cart cookie; Odoo compares price_unit vs list_price. Max delta sent as _price_delta_bps.",
    when: "absolute price delta bps > maxDeltaBps",
    defaults: { maxDeltaBps: 100 },
    merchantPolicyKey: "r015",
    merchantConfig: "maxDeltaBps",
    examples: ["Price changed by 8 percent after mandate -> BLOCK"],
  },
  {
    code: "R016",
    name: "STOCK_CONFIDENCE_GUARD",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: false,
    description: "Escalates low-stock or oversell-risk carts.",
    when: "lowestStock < minStock",
    defaults: { minStock: 1 },
    merchantPolicyKey: "r016",
    merchantConfig: "minStock",
    examples: ["Only 0 units confirmed for cart SKU -> BLOCK"],
  },
  {
    code: "R017",
    // Canonical code is `R017.discount-anomaly-applied`. The old
    // `coupon-discount-anomaly` name was retired (it claimed scrape detection
    // the evaluator does not do) and resolves forward via
    // LEGACY_RULE_CODE_ALIASES.
    name: "DISCOUNT_ANOMALY_APPLIED",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: false,
    description:
      "Blocks anomalous discounts ALREADY APPLIED to the cart: how many discount codes are on it, and the total discount depth. It does not detect coupon scraping from the cart — a rejected code never reaches discountCodes. Failed attempts count only where the server-side couponAttemptFailedCount lookup is wired (it takes precedence, since an agent can under-report the _discount_codes_tried attribute).",
    when: "codes applied to the cart > maxAttempts OR discount bps > maxDiscountBps",
    defaults: { maxAttempts: 5, maxDiscountBps: 5000, windowSeconds: 3600 },
    merchantPolicyKey: "r017",
    merchantConfig:
      "maxAttempts, maxDiscountBps, windowSeconds (dedicated failed-attempt lookup only)",
    examples: [
      "Cart already carries 12 discount codes -> BLOCK",
      "Agent tries 12 codes and all are rejected -> only caught where the couponAttemptFailedCount lookup is wired",
    ],
  },
  {
    code: "R018",
    name: "CART_COMPOSITION_GUARD",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: false,
    description: "Escalates unusual cart size, quantity, or value patterns.",
    when: "cart exceeds avg multiplier, max item count, or max single-SKU quantity",
    defaults: { spikeMultiplier: 5.0 },
    merchantPolicyKey: "r018",
    merchantConfig:
      "merchantAvgOrderCents, spikeMultiplier, maxItemCount, maxSingleSkuQty",
    examples: ["Cart is 10x merchant average order value -> BLOCK"],
  },
  {
    code: "R019",
    name: "COUNTRY_JURISDICTION",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: false,
    description:
      "Restricts billing or shipping countries for merchant policy reasons.",
    when: "country in blockedCountries OR country not in allowedCountries",
    defaults: {},
    merchantPolicyKey: "r019",
    merchantConfig: "allowedCountries, blockedCountries",
    examples: ["Merchant ships only ES/PT and order is US -> BLOCK"],
  },
  {
    code: "R020",
    name: "BUSINESS_HOURS",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: false,
    description:
      "Limits agent checkout to configured merchant business hours. When _merchant_local_hour is not provided, the server computes the current merchant local hour using Intl.DateTimeFormat with the merchant's configured timezone.",
    when: "merchant local hour outside startHour/endHour",
    defaults: {},
    merchantPolicyKey: "r020",
    merchantConfig: "timezone, startHour, endHour",
    examples: [
      "B2B merchant accepts agent orders 9-18 only -> BLOCK after hours",
    ],
  },
  {
    code: "R021",
    name: "FIRST_PURCHASE_WITH_MERCHANT",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: true,
    description: "Escalates first-time agents for this merchant.",
    when: "completedOrders(agentId, merchantId) < minCompletedOrders",
    defaults: { minCompletedOrders: 1 },
    merchantPolicyKey: "r021",
    merchantConfig: "minCompletedOrders",
    examples: ["Known agent, first order in this store -> REVIEW/BLOCK"],
  },
  {
    code: "R022",
    name: "PAYMENT_RAIL_RESTRICTION",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: false,
    description:
      "Restricts payment methods or rails accepted for agent checkout.",
    when: "payment method is blocked or not in allowedPaymentMethods",
    defaults: {},
    merchantPolicyKey: "r022",
    merchantConfig: "allowedPaymentMethods, blockedPaymentMethods",
    examples: ["Merchant disables BNPL for agents -> BLOCK"],
  },
  {
    code: "R023",
    name: "REFUND_ABUSE_GUARD",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: true,
    description: "Blocks agents with a high refund ratio.",
    when: "refundRatio(agentId, windowDays) > maxRatio",
    defaults: { windowDays: 90, maxRatio: 0.5 },
    merchantPolicyKey: "r023",
    merchantConfig: "windowDays, maxRatio",
    examples: ["70 percent refund ratio -> BLOCK"],
  },
  {
    code: "R024",
    name: "DISPUTE_HISTORY_GUARD",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: true,
    description: "Blocks agents with excessive payment disputes.",
    when: "disputeCount(agentId, windowDays) > maxDisputes",
    defaults: { windowDays: 30, maxDisputes: 2 },
    merchantPolicyKey: "r024",
    merchantConfig: "windowDays, maxDisputes",
    examples: ["4 disputes in 30 days -> BLOCK"],
  },
  {
    code: "R025",
    name: "SENSITIVE_DELIVERY_ADDRESS",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: false,
    description:
      "Escalates PO boxes, freight forwarders, or other sensitive delivery addresses.",
    when: "shipping address is PO box or freight forwarder",
    defaults: { blockPoBox: true, blockFreightForwarder: true },
    merchantPolicyKey: "r025",
    merchantConfig: "blockPoBox, blockFreightForwarder",
    examples: ["High-value order to freight forwarder -> BLOCK"],
  },
  {
    code: "R026",
    name: "SUBSCRIPTION_AUTORENEW_GUARD",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: false,
    description:
      "Requires explicit consent for subscriptions and auto-renewal.",
    when: "subscription or autorenew cart without consent evidence",
    defaults: { requireConsent: true },
    merchantPolicyKey: "r026",
    merchantConfig: "requireConsent",
    examples: ["Agent adds annual renewal without consent -> BLOCK"],
  },
  {
    code: "R027",
    name: "GIFT_CARD_STORED_VALUE",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: false,
    description: "Escalates stored-value goods such as gift cards.",
    when: "storedValueCents > maxStoredValueCents",
    defaults: { maxStoredValueCents: 0 },
    merchantPolicyKey: "r027",
    merchantConfig: "maxStoredValueCents",
    examples: ["Agent buys EUR 500 in gift cards -> BLOCK"],
  },
  {
    code: "R028",
    name: "B2B_PO_GUARD",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: false,
    description: "Requires purchase-order evidence for B2B checkout.",
    when: "b2b order and purchaseOrderHash missing",
    defaults: { requirePurchaseOrder: true },
    merchantPolicyKey: "r028",
    merchantConfig: "requirePurchaseOrder",
    examples: ["B2B order without PO number/hash -> BLOCK"],
  },
  {
    code: "R029",
    name: "MERCHANT_PRESET",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: false,
    description:
      "Applies Abierto, Equilibrado, Estricto, or Regulado merchant preset friction.",
    when: "preset-specific minimum evidence is missing",
    defaults: { preset: "equilibrado" },
    merchantPolicyKey: "r029",
    merchantConfig: "preset ('abierto'|'equilibrado'|'estricto'|'regulado')",
    examples: ["Regulado preset without regulated evidence -> BLOCK"],
  },
  {
    code: "R030",
    name: "SIMPLE_CONTROLS",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: false,
    description:
      "Applies basic merchant controls such as max amount and allowed countries.",
    when: "cartTotalCents > maxAmountCents OR country outside allowedCountries",
    defaults: {},
    merchantPolicyKey: "r030",
    merchantConfig: "maxAmountCents, allowedCountries",
    examples: [
      "Merchant sets max EUR 100 for agents; cart is EUR 180 -> BLOCK",
    ],
  },
  // ── R031–R062 — derived from each evaluator in
  // `packages/shared/src/enforcement/rule-catalog.ts`, not from the rule names.
  // `when` mirrors the actual branch that returns HIT; `defaults` only lists a
  // value the evaluator really falls back to. A cap with no default is stated as
  // such: those rules are inert until the merchant configures them.
  {
    code: "R031",
    name: "AGENT_COMMERCE_DISABLED",
    tier: 1,
    action: "BLOCK",
    configurable: false,
    needsLookup: false,
    description:
      "Merchant kill-switch: blocks every agent purchase while enabled. Human checkout is unaffected.",
    when: "an agent is present (any agentic checkout)",
    defaults: {},
    merchantPolicyKey: "r031",
    merchantConfig: "none — enabling the rule IS the configuration",
    examples: [
      "Agent checkout while enabled -> BLOCK",
      "Human checkout -> PASS (rule only applies to agents)",
    ],
  },
  {
    code: "R032",
    name: "CATEGORY_BLOCKLIST",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: false,
    description:
      "Blocks agent purchases of products in merchant-listed categories. Matches the raw cart categories first, then retries against the platform-normalised taxonomy.",
    when: "any cart category is in blockedCategoryIds (raw match, or canonical match after normalising by platform)",
    defaults: { blockedCategoryIds: [] },
    merchantPolicyKey: "r032",
    merchantConfig: "blockedCategoryIds (empty = rule inert)",
    examples: [
      "blockedCategoryIds ['alcohol'], cart declares 'alcohol' -> BLOCK",
      "Cart declares no categories -> PASS (no signal, never assumed)",
    ],
  },
  {
    code: "R034",
    name: "SKU_BLOCKLIST",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: false,
    description:
      "Per-SKU escape hatch for when catalogue categorisation is incomplete.",
    when: "any line item id is in blockedSkus",
    defaults: { blockedSkus: [] },
    merchantPolicyKey: "r034",
    merchantConfig: "blockedSkus (empty = rule inert)",
    examples: ["blockedSkus ['SKU-9'], cart contains SKU-9 -> BLOCK"],
  },
  {
    code: "R035",
    name: "MAX_ORDER_VALUE",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: false,
    description:
      "Caps the total agent order amount. Merchant-side financial guard, independent of any mandate signed by the agent.",
    when: "cartTotalCents > maxCents",
    defaults: {},
    merchantPolicyKey: "r035",
    merchantConfig: "maxCents — NO default: unset means the rule never fires",
    examples: ["maxCents 50000, cart 74900 -> BLOCK"],
  },
  {
    code: "R036",
    name: "MAX_LINE_ITEM_VALUE",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: false,
    description:
      "Caps the per-line subtotal, so one expensive item cannot hide inside a small-looking cart.",
    when: "for any line, qty * priceCents > maxCentsPerLine",
    defaults: {},
    merchantPolicyKey: "r036",
    merchantConfig: "maxCentsPerLine — NO default (note: NOT `maxCents`)",
    examples: ["maxCentsPerLine 20000, line of 2 x 15000 = 30000 -> BLOCK"],
  },
  {
    code: "R038",
    name: "MAX_ITEMS_PER_ORDER",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: false,
    description: "Caps the total piece count per order. Anti-hoarding control.",
    when: "itemCount (sum of units, not lines) > maxQuantity",
    defaults: {},
    merchantPolicyKey: "r038",
    merchantConfig: "maxQuantity — NO default",
    examples: ["maxQuantity 10, cart of 1 line with 24 units -> BLOCK"],
  },
  {
    code: "R039",
    name: "MAX_QUANTITY_PER_SKU",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: false,
    description:
      "Caps quantity per individual SKU. Anti-scalping and resale prevention.",
    when: "any line qty > maxPerSku",
    defaults: {},
    merchantPolicyKey: "r039",
    merchantConfig: "maxPerSku — NO default",
    examples: ["maxPerSku 2, line with qty 5 -> BLOCK"],
  },
  {
    code: "R041",
    name: "MAX_ORDERS_PER_HOUR_MERCHANT",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: true,
    description:
      "Caps SUCCESSFUL orders at the merchant in a rolling 1h window across ALL agents. Anti-burst control at merchant scope.",
    when: "merchant-wide successful orders in the last 3600s > maxPerHour",
    defaults: {},
    merchantPolicyKey: "r041",
    merchantConfig: "maxPerHour — NO default. Window is fixed at 1h",
    examples: ["maxPerHour 20, 21 merchant orders in the last hour -> BLOCK"],
  },
  {
    code: "R042",
    name: "MAX_ORDERS_PER_AGENT_DAY",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: true,
    description:
      "Caps successful orders per agent per 24h window. Complements R011, which counts failures rather than successes.",
    when: "completed orders by this agent in the last 86400s > maxPerAgent",
    defaults: {},
    merchantPolicyKey: "r042",
    merchantConfig: "maxPerAgent — NO default. Window is fixed at 24h",
    examples: [
      "maxPerAgent 5, agent completed 6 orders today -> BLOCK",
      "No agent present -> PASS (agent-scoped rule)",
    ],
  },
  {
    code: "R043",
    name: "AGENT_CHECKOUT_APPROVAL_REQUIRED",
    tier: 2,
    action: "REVIEW",
    configurable: false,
    needsLookup: false,
    description:
      "Routes every agent order through manual merchant approval (HITL). The cart is frozen, not cancelled, and resumes when the merchant approves.",
    when: "an agent is present",
    defaults: {},
    merchantPolicyKey: "r043",
    merchantConfig:
      "ttlMinutes for the approval window (service-side default 60)",
    examples: ["Any agent checkout -> REVIEW (awaits merchant decision)"],
  },
  {
    code: "R044",
    name: "FIRST_N_APPROVAL",
    tier: 2,
    action: "REVIEW",
    configurable: true,
    needsLookup: true,
    description:
      "Routes an agent's first N completed orders at this merchant through approval, then stops. Self-disarming: it lapses once the agent has history.",
    when: "the agent's LIFETIME completed orders at this merchant < firstN",
    defaults: { firstN: 1 },
    merchantPolicyKey: "r044",
    merchantConfig: "firstN (default 1). firstN <= 0 disables the rule",
    examples: [
      "firstN 3, agent has 1 completed order -> REVIEW",
      "firstN 3, agent has 3 completed orders -> PASS (self-disarmed)",
    ],
  },
  {
    code: "R045",
    name: "PROVIDER_ALLOWLIST",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: false,
    description:
      "Admits only buying agents from merchant-listed providers. An agent whose provider cannot be resolved is BLOCKED — fail-closed, unlike R046.",
    when: "allowedProviderIds is non-empty AND (provider unknown OR provider not in the list)",
    defaults: { allowedProviderIds: [] },
    merchantPolicyKey: "r045",
    merchantConfig: "allowedProviderIds (empty = rule inert)",
    examples: [
      "allowlist ['openai'], agent provider 'anthropic' -> BLOCK",
      "allowlist ['openai'], provider unresolvable -> BLOCK (fail-closed)",
    ],
  },
  {
    code: "R046",
    name: "PROVIDER_BLOCKLIST",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: false,
    description:
      "Blocks buying agents from listed providers. An agent whose provider cannot be resolved PASSES — fail-open, the mirror image of R045.",
    when: "blockedProviderIds is non-empty AND the resolved provider is in the list",
    defaults: { blockedProviderIds: [] },
    merchantPolicyKey: "r046",
    merchantConfig: "blockedProviderIds (empty = rule inert)",
    examples: [
      "blocklist ['acme-bot'], agent provider 'acme-bot' -> BLOCK",
      "blocklist ['acme-bot'], provider unresolvable -> PASS (fail-open)",
    ],
  },
  {
    code: "R047",
    name: "CUSTOMER_CONFIRMATION_REQUIRED",
    tier: 2,
    action: "REVIEW",
    configurable: false,
    needsLookup: false,
    description:
      "Requires the buyer to confirm an agent-initiated order out of band (email or SMS link) before payment is captured. Distinct from R043, which asks the MERCHANT.",
    when: "an agent is present AND the cart carries a customer email or phone",
    defaults: {},
    merchantPolicyKey: "r047",
    merchantConfig: "none — the contact channel comes from the cart",
    examples: [
      "Agent checkout with customer email present -> REVIEW",
      "Agent checkout with neither email nor phone -> PASS (no channel to confirm through)",
    ],
  },
  {
    code: "R048",
    name: "NO_DIGITAL_GOODS_FOR_AGENTS",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: false,
    description:
      "Blocks gift cards, license keys, downloadables and stored-value products for agent purchases — the classic instant-resale vector.",
    when: "the cart declares a digital good type present in blockedTypes",
    defaults: {
      blockedTypes: [
        "gift_card",
        "license_key",
        "downloadable",
        "stored_value",
      ],
    },
    merchantPolicyKey: "r048",
    merchantConfig:
      "blockedTypes — unlike the other lists, this one HAS a default; an explicitly empty array disables the rule",
    examples: [
      "Cart declares 'gift_card' -> BLOCK (default list)",
      "Cart declares no digital good type -> PASS",
    ],
  },
  {
    code: "R062",
    name: "MAX_SPEND_PER_AGENT_WINDOW",
    tier: 2,
    action: "BLOCK",
    configurable: true,
    needsLookup: true,
    description:
      "Caps CUMULATIVE agent spend at this merchant within a rolling window. Complements R035, which caps a single order: ten orders just under the per-order cap still trip this one.",
    when: "spend already completed in the window PLUS the current cart total > maxSpendCents",
    defaults: { windowSeconds: 86400 },
    merchantPolicyKey: "r062",
    merchantConfig:
      "maxSpendCents (NO default — unset means inert) and windowSeconds (default 86400)",
    examples: [
      "maxSpendCents 100000, 90000 spent today, cart 15000 -> BLOCK (projected 105000)",
      "Same caps, cart 5000 -> PASS (projected 95000)",
    ],
  },
] as const;
